name: version
on:
  push:
    branches:
    - main

permissions:
  packages: write
  contents: write
  issues: write
  pull-requests: write

jobs:

  validate:
    uses: unbounded-tech/workflows-crossplane/.github/workflows/validate.yaml@v0.8.0
    with:
      examples: |
        [
          "examples/identitycenters/example-minimal.yaml",
          "examples/identitycenters/example-groups.yaml"
        ]
      api_path: apis/identitycenters
      error_on_missing_schemas: true

  test:
    uses: unbounded-tech/workflows-crossplane/.github/workflows/test.yaml@v0.8.0

  version-and-tag:
    name: Version and Tag
    needs:
      - validate
      - test
    uses: unbounded-tech/workflow-vnext-tag/.github/workflows/workflow.yaml@v1.19.1
    secrets: inherit
    with:
      useDeployKey: true
      yqPatches: |
        patches:
          - filePath: .gitops/deploy/values.yaml
            selector: .version
            valuePrefix: "v"
          - filePath: .gitops/deploy/Chart.yaml
            selector: .version
            valuePrefix: ""
